# -*- coding: utf-8 -*-
"""transformers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PfEPgMlxmOWktKKQjexghNuGECn0yYAq
"""

!pip install transformers

from transformers import pipeline

"""SENTIMENTAL ANALYSIS"""

analyzer=pipeline('sentiment-analysis')

text_input=input("enter some text:")

result=analyzer(text_input)

result

"""TEXT GENERATION"""

generate=pipeline('text-generation')

statement=input("enter any short statement:")

result=generate(statement)

result

"""NAMED ENTITY RECOGNITION"""

entity_recog=pipeline('ner')

s=input("enter a statement:")

res=entity_recog(s)

res

"""QUESTION ANSWERING"""

q_a=pipeline('question-answering')

result=q_a({
    'question':'What might be the role of sensors in an IoT system?',
    'context':'The Internet of Things (IoT) is a system of interrelated devices that are connected via the internet and can collect, share, and act on data. These devices can include anything from home appliances to industrial machines. With sensors and software, IoT devices can communicate with each other and with humans, making processes more efficient and automated. Examples include smart homes, wearable fitness trackers, and smart cities that monitor traffic and pollution levels.'

})

result

"""SUMMARIZATION"""

summarize=pipeline('summarization')

text=input("enter some text:")

summarized_text=summarize(text,max_length=50)

summarized_text

"""QUESTION AND ANSWER CHATBOT"""

question_answer=pipeline('question-answering')

while True:
    q = input("Enter your question (type 'end' to exit): ")
    if q== "end":
        break
    res = question_answer({
        'question': q,
        'context': """I recently bought a stylish black laptop from Amazon for ₹80,000 after careful research. What first caught my attention was its sleek and modern design, which looks premium and professional. It's perfect for both work and gaming. The laptop comes with 16GB of RAM, making multitasking smooth and effortless. I can run heavy software, switch between apps quickly, and enjoy a lag-free experience. It also has 1TB of internal storage, which is more than enough for storing games, videos, documents, and software without worrying about space. One of the best features is its impressive graphics performance—ideal for gamers like me. High-end games run smoothly with sharp and vibrant visuals, creating a fantastic gaming experience. The device is packed with useful features like a backlit keyboard, fast charging, loud and clear speakers, and multiple connectivity ports including USB and HDMI. It also connects easily with other devices and works great for online classes or video meetings, thanks to its quality webcam and microphone. The overall performance is fast, reliable, and very user-friendly. However, the only drawback I found is its battery life, which is relatively low and often requires charging during long usage sessions. Despite this, the laptop is lightweight, easy to carry, and feels sturdy. The delivery was prompt, packaging was secure, and the setup was simple. I’ve already recommended this laptop to my friends because it feels like a great value for the price. I’m truly satisfied with the purchase and believe it was worth every rupee."""
    })
    print(res['answer'])

"""TRANSLATE"""

from transformers import pipeline

translate=pipeline('translation_en_to_de')

text=input("enter some text:")

res=translate(text)

res

"""FILL MASK"""

f_m=pipeline('fill-mask')

text=input("enter a text with a blank having <mask>")

res=f_m(text)

res

"""FEATURE EXTRACTION"""

feature_extraction=pipeline('feature-extraction')

text=input("enter your text:")

res=feature_extraction(text)

res

"""Question Answering on the image"""

vqa_pipeline=pipeline('visual-question-answering')

image=r'/content/dog.jpeg'

q=input("enter question about image:")
res=vqa_pipeline(image,q)
print(res)